"""Add parsed_text to resumes

Revision ID: 6dec659b4f53
Revises: d5bb76cad5f0
Create Date: 2026-06-22 13:44:54.581018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dec659b4f53'
down_revision: Union[str, Sequence[str], None] = 'd5bb76cad5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('parsed_text', sa.Text(), nullable=True))
    op.drop_constraint(op.f('resumes_user_id_fkey'), 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key(op.f('resumes_user_id_fkey'), 'resumes', 'users', ['user_id'], ['id'])
    op.drop_column('resumes', 'parsed_text')
    # ### end Alembic commands ###
